-- Clean all data except users, app_settings, ad_strategies
DELETE FROM messages;
DELETE FROM bot_states;
DELETE FROM conversations;
DELETE FROM bot_secrets;
DELETE FROM products;
DELETE FROM store_products;
UPDATE stores SET bot_id = NULL;
DELETE FROM stores;
DELETE FROM bots;
DELETE FROM leads;
DELETE FROM landing_pages;
DELETE FROM ad_creatives;
DELETE FROM ad_remote_mappings;
UPDATE ad_drafts SET connected_account_id = NULL;
DELETE FROM ad_drafts;
DELETE FROM ad_campaigns_v2;
DELETE FROM ad_connected_accounts;
DELETE FROM ad_oauth_tokens;
DELETE FROM ad_integrations;
DELETE FROM ad_assets;
DELETE FROM ad_jobs;
DELETE FROM ad_metrics_daily;
DELETE FROM openai_configs;
DELETE FROM business_briefs;
DELETE FROM commissions;
DELETE FROM pack_purchase_requests;
DELETE FROM withdrawal_requests;
DELETE FROM password_reset_tokens;
DELETE FROM audit_logs;
